Scribe = require('../src/scribe')
Scribe.Modules =
  Authorship  : require('../src/modules/authorship')
  LinkTooltip : require('../src/modules/link-tooltip')
  MultiCursor : require('../src/modules/multi-cursor')
  Toolbar     : require('../src/modules/toolbar')
Scribe.Themes =
  ColorPicker : require('../src/themes/color-picker')
  Default     : require('../src/themes/default')
  Picker      : require('../src/themes/picker')
  Snow        : require('../src/themes/snow')
Scribe.Debug         = require('../src/debug')
Scribe.Document      = require('../src/document')
Scribe.DOM           = require('../src/dom')
Scribe.Editor        = require('../src/editor')
Scribe.FormatManager = require('../src/format-manager')
Scribe.Format        = require('../src/format')
Scribe.Keyboard      = require('../src/keyboard')
Scribe.LeafIterator  = require('../src/leaf-iterator')
Scribe.Leaf          = require('../src/leaf')
Scribe.Line          = require('../src/line')
Scribe.Logger        = require('../src/logger')
Scribe.Normalizer    = require('../src/normalizer')
Scribe.PasteManager  = require('../src/paste-manager')
Scribe.Position      = require('../src/position')
Scribe.Range         = require('../src/range')
Scribe.Renderer      = require('../src/renderer')
Scribe.Selection     = require('../src/selection')
Scribe.UndoManager   = require('../src/undo-manager')
Scribe.Utils         = require('../src/utils')


module.exports = Scribe
