// Generated by CoffeeScript 1.3.3
(function() {
  var Selection;

  Selection = (function() {

    function Selection() {}

    return Selection;

  })();

  window.Tandem || (window.Tandem = {});

  window.Tandem.Selection = Selection;

}).call(this);
